version: '3.4'

services:
  venueless:
    image: eventyay/eventyay-video:${TAG}-latest
    container_name: venueless
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=venueless.settings
      - LC_ALL=C.UTF-8
      - IPYTHONDIR=/data/.ipython
      - VENUELESS_COMMIT_SHA=${COMMIT}
      - VENUELESS_DB_TYPE=postgresql
      - VENUELESS_DB_NAME=${POSTGRES_DB}
      - VENUELESS_DB_USER=${POSTGRES_USER}
      - VENUELESS_DB_PASS=${POSTGRES_PASSWD}
      - VENUELESS_DB_HOST=eventyay-db
      - VENUELESS_REDIS_URLS=redis://redis:6379/0,redis://redis1:6379/0
      - VENUELESS_DATA_DIR=/data
      - VENUELESS_MEDIA_URL=http://localhost:8375/media/
      - VENUELESS_REDIS_USE_PUBSUB=true
    volumes:
      - /etc/venueless:/etc/venueless
      - /data:/data
    entrypoint: ["/usr/local/bin/venueless"]
    command: ["all"]
  webapp:
    image: eventyay/eventyay-video:${TAG}-latest
    ports:
      - "8880:8880"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    entrypoint: [""]
    command: ["npm", "start", "--", "--host", "0.0.0.0"]
    working_dir: /venueless/webapp

  redis:
    image: redis:latest
    container_name: redis

  redis1:
    image: redis:latest
    container_name: redis1

  eventyay-db:
    image: postgres:15
    container_name: eventyay-db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=md5
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWD}

volumes:
  postgres_data:
  appdata:
