name: Main workflow
on:
  push:
    branches:
      - development
      - master
      - fixes-94
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker tag
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: odkhang/eventyay-video:${{ env.TAG }}-latest
          
      # - name: Build and push server Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./server
      #     file: ./server/Dockerfile-dev
      #     push: true
      #     tags: odkhang/eventyay-video:${{ env.TAG }}-server

      # - name: Build and push webapp Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./webapp
      #     file: ./webapp/Dockerfile-dev
      #     push: true
      #     tags: odkhang/eventyay-video:${{ env.TAG }}-webapp
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Docker tag
      id: vars
      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Deploy
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        scp docker-compose.yml "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/eventyay/eventyay-videos"
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /home/eventyay/eventyay-videos && sudo docker pull eventyay/eventyay-video:${{ env.TAG }}-server && sudo docker pull eventyay/eventyay-video:${{ env.TAG }}-webapp && sudo docker-compose up -d"
